version: '3.8'

services:
#-------------------------------------
  frontend:
    build:
      context: frontend/
      dockerfile: frontend.Dockerfile
    ports:
      - 5500:5500
    depends_on:
      - backend
#-------------------------------------
  backend:
    build:
      context: backend/
      dockerfile: backend.Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./backend/database:database/
